name: do_it_now
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  google_fonts: ^6.2.1
  color_system: ^0.0.7
  get_storage: ^2.1.1
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  bot_toast: ^4.1.3
  loading_progress_indicator: ^0.1.6
  intl: ^0.20.2
  flutter_animate: ^4.5.2
  image_picker: ^1.1.2
  http: ^1.3.0
  flutter_svg: ^2.0.17
  transparent_image: ^2.0.1
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/logo/
